export const IPC = {
  LOAD_SESSIONS: 'sessions:load',
  SAVE_SESSIONS: 'sessions:save',
  LOAD_SETTINGS: 'settings:load',
  SAVE_SETTINGS: 'settings:save',
  LIST_CLAUDE_SESSIONS: 'claude:list-sessions',
  PICK_FOLDER: 'dialog:pick-folder',
  OPEN_EXTERNAL: 'shell:open-external',
  OPEN_PATH: 'shell:open-path',
  LOCAL_PTY_SPAWN: 'pty:spawn',
  LOCAL_PTY_INPUT: 'pty:input',
  LOCAL_PTY_RESIZE: 'pty:resize',
  LOCAL_PTY_KILL: 'pty:kill',
  LOCAL_PTY_OUTPUT: 'pty:output',
  LOCAL_PTY_EXIT: 'pty:exit',
  CLAUDE_SESSION_DETECTED: 'claude:session-detected',
  TOOL_SESSION_DETECTED: 'tool:session-detected',
  FILE_DROP: 'file:drop',
  SET_ACTIVE_SESSION: 'session:set-active',
  SHOW_NOTIFICATION: 'app:show-notification',
  GET_GIT_BRANCH: 'git:get-branch',
  CREATE_GIT_WORKTREE: 'git:create-worktree',
  READ_FILE: 'fs:read-file',
  WRITE_FILE: 'fs:write-file',
  GET_TOOL_SESSION_SUMMARY: 'tool:get-session-summary',
  FORCE_QUIT: 'app:force-quit',
  // Remote access (host agent)
  REMOTE_GET_STATUS: 'remote:get-status',
  REMOTE_STATUS_CHANGED: 'remote:status-changed',
  REMOTE_SIGN_IN: 'remote:sign-in',
  REMOTE_SIGN_OUT: 'remote:sign-out',
  REMOTE_SET_ENABLED: 'remote:set-enabled',
  REMOTE_SET_DEVICE_NAME: 'remote:set-device-name',
  REMOTE_SET_PREVENT_SLEEP: 'remote:set-prevent-sleep',
  REMOTE_RESET: 'remote:reset',
  REMOTE_GET_VIEWERS: 'remote:get-viewers',
  REMOTE_VIEWERS_CHANGED: 'remote:viewers-changed',
  SESSION_BUSY_CHANGED: 'session:busy-changed',
  // Remote client (viewing other devices' sessions)
  REMOTE_LIST: 'remote:list',
  REMOTE_ATTACH: 'remote:attach',
  REMOTE_INPUT: 'remote:input',
  REMOTE_RESIZE: 'remote:resize',
  REMOTE_DETACH: 'remote:detach',
  REMOTE_TAB_OUTPUT: 'remote:tab-output',
  REMOTE_TAB_STATUS: 'remote:tab-status'
} as const
